sonar.projectKey=David1889_Agiles_TP_10
sonar.organization=grupo10agiles
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.test.inclusion=**/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info